FROM node:22-alpine

RUN corepack enable
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

ARG VITE_SERVER1_API
ARG VITE_SERVER2_SOCKET
ARG VITE_SERVER2_API

RUN cat > .env <<EOF
VITE_SERVER1_API=$VITE_SERVER1_API
VITE_SERVER2_SOCKET=$VITE_SERVER2_SOCKET
VITE_SERVER2_API=$VITE_SERVER2_API
EOF

RUN pnpm build

RUN npm install -g serve

EXPOSE 3000

# Serve the built files
CMD ["serve", "-s", "dist", "-l", "3000"]
