// src/constants/events.js
const CONNECTED = "CONNECTED";        // when a socket connects successfully
const DISCONNECTED = "DISCONNECTED";  // when a socket disconnects

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const NEW_MESSAGE_SEND = "NEW_MESSAGE_SEND";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_MESSAGE_SEEN = "NEW_MESSAGE_SEEN"; // Not used yet, but can be used to mark messages as seen
const NEW_MESSAGE_CONFIRMED = "NEW_MESSAGE_CONFIRMED"; // Not used yet, but can be used to confirm message delivery

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const TYPING_STATUS = "TYPING_STATUS";

const NEW_FRIEND_REQUEST = "NEW_FRIEND_REQUEST";
const NEW_FRIEND_REQUEST_ALERT = "NEW_FRIEND_REQUEST_ALERT"; // Not used yet, but can be used to alert about new friend requests
const FRIEND_REQUEST_ACCEPT = "FRIEND_REQUEST_ACCEPT"

const ONLINE_USERS = "ONLINE_USERS";
const CHECK_ONLINE = "CHECK_ONLINE";

const NEW_NOTIFICATION = "NEW_NOTIFICATION";
const NEW_NOTIFICATION_ALERT = "NEW_NOTIFICATION_ALERT";

export {
  CONNECTED,
  DISCONNECTED,
  CHAT_JOINED,
  CHAT_LEAVED,
  NEW_MESSAGE_SEND,
  NEW_MESSAGE_ALERT,
  NEW_MESSAGE_SEEN,
  NEW_MESSAGE_CONFIRMED,
  START_TYPING,
  STOP_TYPING,
  TYPING_STATUS,
  NEW_FRIEND_REQUEST,
  NEW_FRIEND_REQUEST_ALERT,
  ONLINE_USERS,
  CHECK_ONLINE,
  FRIEND_REQUEST_ACCEPT,
  NEW_NOTIFICATION,
  NEW_NOTIFICATION_ALERT
};
