FROM node:22-alpine

RUN corepack enable
WORKDIR /app

# Copy dependency files
COPY package*.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install

# Copy application code
COPY . .


EXPOSE 9000
CMD ["pnpm", "run", "start"]
